#ifndef PARSEUR_IF_H
#define PARSEUR_IF_H

#include "compiler/ast/registry/context_parser.h"
#include "compiler/lexer/lexer.h"
#include "compiler/parser/interfaces/i_parser.h"
#include "compiler/parser/parser_base.h"
#include <cstddef>

// Do not modify the code; this section is dynamically generated by the Jinja2 template.
class ParserIf : public IParser, public ParserBase
{
private:
    ContextParser& _contextParser;
    
public: 

    ParserIf(ContextParser& contextParser);
    ~ParserIf();
    
    auto parse(std::vector<Token>& tokens, std::size_t& index) -> INode* override;
};


#endif /* PARSEUR_IF_H */




