#include "compiler/visitor/ast_graph_viz/general_visitor_graph_viz.h"
#include "compiler/ast/registry/context_gen_code.h"
#include "compiler/visual_graph/output_visual_graph_text.h"
#include "compiler/visitor/visitor_base_generale.h"
#include "compiler/macros/prysma_maybe_unused.h"

#if 1
// Do not modify the code; this section is dynamically generated by the Jinja2 template.
GeneralVisitorGraphViz::GeneralVisitorGraphViz(ContextGenCode* contextGenCode, OutputVisualGraphText outputVisualGraph)
    : VisitorBaseGenerale(contextGenCode)
    , _outputVisualGraph(std::move(outputVisualGraph))
{}

GeneralVisitorGraphViz::~GeneralVisitorGraphViz()
{}

void GeneralVisitorGraphViz::generate()
{
    _outputVisualGraph.generate();
}

void GeneralVisitorGraphViz::visiter(NodeInstruction* nodeInstruction)
{
    auto& nodeInstructionData = _contextGenCode->getNodeDataRegistry()->get(nodeInstruction);

    (void)nodeInstruction;
    int idNode = _outputVisualGraph.addNode("Instruction"); // size_t ?
    for (auto* element : nodeInstructionData.getChildren())
    {
        element->accept(this);
        
        int idChild = _pileIds.top();
        _pileIds.pop();

        _outputVisualGraph.addEdge(idNode, idChild);
    }
    _pileIds.push(idNode);
}
void GeneralVisitorGraphViz::visiter(NodeCallFunction* nodeCallFunction)
{
    auto& nodeCallFunctionData = _contextGenCode->getNodeDataRegistry()->get(nodeCallFunction);

    (void)nodeCallFunction;
     int idNode = _outputVisualGraph.addNode(nodeCallFunctionData.getName().value.str());
     for (auto* element : nodeCallFunctionData.getChildren())
     {
         element->accept(this);

         int idChild = _pileIds.top();
         _pileIds.pop();

         _outputVisualGraph.addEdge(idNode, idChild);
     }
     _pileIds.push(idNode);
}
void GeneralVisitorGraphViz::visiter(NodeArgFunction* nodeArgFunction)
{
    auto& nodeArgFunctionData = _contextGenCode->getNodeDataRegistry()->get(nodeArgFunction);

    (void)nodeArgFunction;

    int idNode = _outputVisualGraph.addNode(nodeArgFunctionData.getName().value.str());
    _pileIds.push(idNode);
}
void GeneralVisitorGraphViz::visiter(NodeDeclarationFunction* nodeDeclarationFunction)
{
    auto& nodeDeclarationFunctionData = _contextGenCode->getNodeDataRegistry()->get(nodeDeclarationFunction);

    (void)nodeDeclarationFunction;
    int idNode = _outputVisualGraph.addNode(nodeDeclarationFunctionData.getVisibility().value.str());
    for (auto* element : nodeDeclarationFunctionData.getArguments())
    {
        element->accept(this);

        int idChild = _pileIds.top();
        _pileIds.pop();

        _outputVisualGraph.addEdge(idNode, idChild);
    }
    if (nodeDeclarationFunctionData.getBody() != nullptr)
    {
        nodeDeclarationFunctionData.getBody()->accept(this);

        int idChild = _pileIds.top();
        _pileIds.pop();

        _outputVisualGraph.addEdge(idNode, idChild);
    }
    _pileIds.push(idNode);
}
void GeneralVisitorGraphViz::visiter(NodeReturn* nodeReturn)
{
    auto& nodeReturnData = _contextGenCode->getNodeDataRegistry()->get(nodeReturn);

    int idNode = _outputVisualGraph.addNode("Return");

    if (nodeReturnData.getReturnValue() != nullptr)
    {
        nodeReturnData.getReturnValue()->accept(this);

        int idChild = _pileIds.top();
        _pileIds.pop();

        _outputVisualGraph.addEdge(idNode, idChild);
    }

    _pileIds.push(idNode);
}
void GeneralVisitorGraphViz::visiter(NodeAssignmentVariable* nodeAssignmentVariable)
{
    auto& nodeAssignmentVariableData = _contextGenCode->getNodeDataRegistry()->get(nodeAssignmentVariable);

    int idNode = _outputVisualGraph.addNode(nodeAssignmentVariableData.getName().value.str());
    if (nodeAssignmentVariableData.getExpression() != nullptr)
    {
        nodeAssignmentVariableData.getExpression()->accept(this);

        int idChild = _pileIds.top();
        _pileIds.pop();

        _outputVisualGraph.addEdge(idNode, idChild);
    }

    _pileIds.push(idNode);
}
void GeneralVisitorGraphViz::visiter(NodeDeclarationVariable* nodeDeclarationVariable)
{
    auto& nodeDeclarationVariableData = _contextGenCode->getNodeDataRegistry()->get(nodeDeclarationVariable);

    int idNode = _outputVisualGraph.addNode(nodeDeclarationVariableData.getVisibility().value.str());
    if (nodeDeclarationVariableData.getExpression() != nullptr)
    {
        nodeDeclarationVariableData.getExpression()->accept(this);

        int idChild = _pileIds.top();
        _pileIds.pop();

        _outputVisualGraph.addEdge(idNode, idChild);
    }
    _pileIds.push(idNode);
}
void GeneralVisitorGraphViz::visiter(NodeRefVariable* nodeRefVariable)
{
    auto& nodeRefVariableData = _contextGenCode->getNodeDataRegistry()->get(nodeRefVariable);

    int idNode = _outputVisualGraph.addNode(nodeRefVariableData.getName().value.str());
    _pileIds.push(idNode);
}
void GeneralVisitorGraphViz::visiter(NodeUnRefVariable* nodeUnRefVariable)
{
    auto& nodeUnRefVariableData = _contextGenCode->getNodeDataRegistry()->get(nodeUnRefVariable);

    int idNode = _outputVisualGraph.addNode(nodeUnRefVariableData.getName().value.str());
    _pileIds.push(idNode);
}
void GeneralVisitorGraphViz::visiter(NodeIdentifiant* nodeIdentifiant PRYSMA_MAYBE_UNUSED)
{
    int idNode = _outputVisualGraph.addNode("Identifiant");
    _pileIds.push(idNode);
}
void GeneralVisitorGraphViz::visiter(NodeAssignmentArray* nodeAssignmentArray)
{
    auto& nodeAssignmentArrayData = _contextGenCode->getNodeDataRegistry()->get(nodeAssignmentArray);

    int idNode = _outputVisualGraph.addNode(nodeAssignmentArrayData.getName().value.str());
    if (nodeAssignmentArrayData.getExpressionIndex() != nullptr)
    {
        nodeAssignmentArrayData.getExpressionIndex()->accept(this);

        int idChild = _pileIds.top();
        _pileIds.pop();

        _outputVisualGraph.addEdge(idNode, idChild);
    }

    if (nodeAssignmentArrayData.getExpression() != nullptr)
    {
        nodeAssignmentArrayData.getExpression()->accept(this);

        int idChild = _pileIds.top();
        _pileIds.pop();

        _outputVisualGraph.addEdge(idNode, idChild);
    }
    _pileIds.push(idNode);
}
void GeneralVisitorGraphViz::visiter(NodeArrayInitialization* nodeArrayInitialization)
{
    auto& nodeArrayInitializationData = _contextGenCode->getNodeDataRegistry()->get(nodeArrayInitialization);

    int idNode = _outputVisualGraph.addNode("ArrayInitialization");
    for (auto* element : nodeArrayInitializationData.getElements())
    {
        element->accept(this);

        int idChild = _pileIds.top();
        _pileIds.pop();

        _outputVisualGraph.addEdge(idNode, idChild);
    }
    _pileIds.push(idNode);
}
void GeneralVisitorGraphViz::visiter(NodeReadingArray* nodeReadingArray)
{
    auto& nodeReadingArrayData = _contextGenCode->getNodeDataRegistry()->get(nodeReadingArray);

    int idNode = _outputVisualGraph.addNode(nodeReadingArrayData.getName().value.str());
    if (nodeReadingArrayData.getIndexEquation() != nullptr)
    {
        nodeReadingArrayData.getIndexEquation()->accept(this);

        int idChild = _pileIds.top();
        _pileIds.pop();

        _outputVisualGraph.addEdge(idNode, idChild);
    }
    _pileIds.push(idNode);
}
void GeneralVisitorGraphViz::visiter(NodeClass* nodeClass)
{
    auto& nodeClassData = _contextGenCode->getNodeDataRegistry()->get(nodeClass);

    int idNode = _outputVisualGraph.addNode(nodeClassData.getName().value.str());

    for (auto* element : nodeClassData.getInheritance())
    {
        element->accept(this);

        int idChild = _pileIds.top();
        _pileIds.pop();

        _outputVisualGraph.addEdge(idNode, idChild);
    }

    for (auto* element : nodeClassData.getMembers())
    {
        element->accept(this);

        int idChild = _pileIds.top();
        _pileIds.pop();

        _outputVisualGraph.addEdge(idNode, idChild);
    }

    for (auto* element : nodeClassData.getBuilder()) // mettre un s a Builder(s)
    {
        element->accept(this);

        int idChild = _pileIds.top();
        _pileIds.pop();

        _outputVisualGraph.addEdge(idNode, idChild);
    }
    _pileIds.push(idNode);
}
void GeneralVisitorGraphViz::visiter(NodeCallObject* nodeCallObject)
{
    auto& nodeCallObjectData = _contextGenCode->getNodeDataRegistry()->get(nodeCallObject);

    int idNode = _outputVisualGraph.addNode(nodeCallObjectData.getObjectName().value.str());
    for (auto* element : nodeCallObjectData.getChildren())
    {
        element->accept(this);

        int idChild = _pileIds.top();
        _pileIds.pop();

        _outputVisualGraph.addEdge(idNode, idChild);
    }
    _pileIds.push(idNode);
}
void GeneralVisitorGraphViz::visiter(NodeAccesAttribute* nodeAccesAttribute)
{
    auto& nodeAccesAttributeData = _contextGenCode->getNodeDataRegistry()->get(nodeAccesAttribute);

    int idNode = _outputVisualGraph.addNode(nodeAccesAttributeData.getObjectName().value.str());
    _pileIds.push(idNode);
}
void GeneralVisitorGraphViz::visiter(NodeDeclarationObject* nodeDeclarationObject)
{
    auto& nodeDeclarationObjectData = _contextGenCode->getNodeDataRegistry()->get(nodeDeclarationObject);

    int idNode = _outputVisualGraph.addNode(nodeDeclarationObjectData.getObjectName().value.str());
    _pileIds.push(idNode);
}
void GeneralVisitorGraphViz::visiter(NodeIf* nodeIf)
{
    auto& nodeIfData = _contextGenCode->getNodeDataRegistry()->get(nodeIf);

    int idNode = _outputVisualGraph.addNode("If");

    if (nodeIfData.getNodeCondition() != nullptr)
    {
        nodeIfData.getNodeCondition()->accept(this);
        int idChild = _pileIds.top();
        _pileIds.pop();
        _outputVisualGraph.addEdge(idNode, idChild);
    }

    if (nodeIfData.getNodeBlocIf() != nullptr)
    {
        nodeIfData.getNodeBlocIf()->accept(this);
        int idChild = _pileIds.top();
        _pileIds.pop();
        _outputVisualGraph.addEdge(idNode, idChild);
    }

    if (nodeIfData.getNodeBlocElse() != nullptr)
    {
        nodeIfData.getNodeBlocElse()->accept(this);
        int idChild = _pileIds.top();
        _pileIds.pop();
        _outputVisualGraph.addEdge(idNode, idChild);
    }

    if (nodeIfData.getNodeBlocEndif() != nullptr)
    {
        nodeIfData.getNodeBlocEndif()->accept(this);
        int idChild = _pileIds.top();
        _pileIds.pop();
        _outputVisualGraph.addEdge(idNode, idChild);
    }
    _pileIds.push(idNode);
}
void GeneralVisitorGraphViz::visiter(NodeNew* nodeNew)
{
    auto& nodeNewData = _contextGenCode->getNodeDataRegistry()->get(nodeNew);

    int idNode = _outputVisualGraph.addNode(nodeNewData.getName().value.str());
    for (auto* element : nodeNewData.getArguments())
    {
        element->accept(this);
        int idChild = _pileIds.top();
        _pileIds.pop();
        _outputVisualGraph.addEdge(idNode, idChild);
    }
    _pileIds.push(idNode);
}
void GeneralVisitorGraphViz::visiter(NodeDelete* nodeDelete)
{
    auto& nodeDeleteData = _contextGenCode->getNodeDataRegistry()->get(nodeDelete);

    int idNode = _outputVisualGraph.addNode(nodeDeleteData.getName().value.str());
    _pileIds.push(idNode);
}
void GeneralVisitorGraphViz::visiter(NodeInclude* nodeInclude)
{
    auto& nodeIncludeData = _contextGenCode->getNodeDataRegistry()->get(nodeInclude);

    int idNode = _outputVisualGraph.addNode(nodeIncludeData.getPath().value.str());
    _pileIds.push(idNode);
}
void GeneralVisitorGraphViz::visiter(NodeWhile* nodeWhile)
{
    auto& nodeWhileData = _contextGenCode->getNodeDataRegistry()->get(nodeWhile);

    int idNode = _outputVisualGraph.addNode("While");

    if (nodeWhileData.getNodeCondition() != nullptr)
    {
        nodeWhileData.getNodeCondition()->accept(this);
        int idChild = _pileIds.top();
        _pileIds.pop();
        _outputVisualGraph.addEdge(idNode, idChild);
    }

    if (nodeWhileData.getWhileBlock() != nullptr)
    {
        nodeWhileData.getWhileBlock()->accept(this);
        int idChild = _pileIds.top();
        _pileIds.pop();
        _outputVisualGraph.addEdge(idNode, idChild);
    }

    if (nodeWhileData.getWhileEndBlock() != nullptr)
    {
        nodeWhileData.getWhileEndBlock()->accept(this);
        int idChild = _pileIds.top();
        _pileIds.pop();
        _outputVisualGraph.addEdge(idNode, idChild);
    }
    _pileIds.push(idNode);
}
void GeneralVisitorGraphViz::visiter(NodeOperation* nodeOperation)
{
    auto& nodeOperationData = _contextGenCode->getNodeDataRegistry()->get(nodeOperation);

    int idNode = _outputVisualGraph.addNode(nodeOperationData.getToken().value.str());
    if (nodeOperationData.getLeft() != nullptr)
    {
        nodeOperationData.getLeft()->accept(this);
        int idChild = _pileIds.top();
        _pileIds.pop();
        _outputVisualGraph.addEdge(idNode, idChild);
    }

    if (nodeOperationData.getRight() != nullptr)
    {
        nodeOperationData.getRight()->accept(this);
        int idChild = _pileIds.top();
        _pileIds.pop();
        _outputVisualGraph.addEdge(idNode, idChild);
    }
    _pileIds.push(idNode);
}
void GeneralVisitorGraphViz::visiter(NodeLiteral* nodeLiteral)
{
    auto& nodeLiteralData = _contextGenCode->getNodeDataRegistry()->get(nodeLiteral);

    int idNode = _outputVisualGraph.addNode(nodeLiteralData.getToken().value.str());
    _pileIds.push(idNode);
}
void GeneralVisitorGraphViz::visiter(NodeNegation* nodeNegation)
{
    auto& nodeNegationData = _contextGenCode->getNodeDataRegistry()->get(nodeNegation);

    int idNode = _outputVisualGraph.addNode(nodeNegationData.getOp().value.str());
    if (nodeNegationData.getOperand() != nullptr)
    {
        nodeNegationData.getOperand()->accept(this);
        int idChild = _pileIds.top();
        _pileIds.pop();
        _outputVisualGraph.addEdge(idNode, idChild);
    }
    _pileIds.push(idNode);
}
void GeneralVisitorGraphViz::visiter(NodeString* nodeString PRYSMA_MAYBE_UNUSED)
{
    int idNode = _outputVisualGraph.addNode("String");
    _pileIds.push(idNode);
}
#endif