#ifndef VISITEUR_BASE_GENERALE_H
#define VISITEUR_BASE_GENERALE_H

#include "compiler/ast/registry/context_gen_code.h"
#include "compiler/visitor/interfaces/i_visitor.h"

// Do not modify the code; this section is dynamically generated by the Jinja2 template.
class NodeInstruction;
class NodeCallFunction;
class NodeArgFunction;
class NodeDeclarationFunction;
class NodeReturn;
class NodeAssignmentVariable;
class NodeDeclarationVariable;
class NodeRefVariable;
class NodeUnRefVariable;
class NodeIdentifiant;
class NodeAssignmentArray;
class NodeArrayInitialization;
class NodeReadingArray;
class NodeClass;
class NodeCallObject;
class NodeAccesAttribute;
class NodeDeclarationObject;
class NodeIf;
class NodeNew;
class NodeDelete;
class NodeInclude;
class NodeWhile;
class NodeOperation;
class NodeLiteral;
class NodeNegation;
class NodeString;

class VisitorBaseGenerale : public IVisitor
{
public:
    VisitorBaseGenerale(ContextGenCode* ctx);

    void visiter(NodeInstruction* nodeInstruction) override;
    void visiter(NodeCallFunction* nodeCallFunction) override;
    void visiter(NodeArgFunction* nodeArgFunction) override;
    void visiter(NodeDeclarationFunction* nodeDeclarationFunction) override;
    void visiter(NodeReturn* nodeReturn) override;
    void visiter(NodeAssignmentVariable* nodeAssignmentVariable) override;
    void visiter(NodeDeclarationVariable* nodeDeclarationVariable) override;
    void visiter(NodeRefVariable* nodeRefVariable) override;
    void visiter(NodeUnRefVariable* nodeUnRefVariable) override;
    void visiter(NodeIdentifiant* nodeIdentifiant) override;
    void visiter(NodeAssignmentArray* nodeAssignmentArray) override;
    void visiter(NodeArrayInitialization* nodeArrayInitialization) override;
    void visiter(NodeReadingArray* nodeReadingArray) override;
    void visiter(NodeClass* nodeClass) override;
    void visiter(NodeCallObject* nodeCallObject) override;
    void visiter(NodeAccesAttribute* nodeAccesAttribute) override;
    void visiter(NodeDeclarationObject* nodeDeclarationObject) override;
    void visiter(NodeIf* nodeIf) override;
    void visiter(NodeNew* nodeNew) override;
    void visiter(NodeDelete* nodeDelete) override;
    void visiter(NodeInclude* nodeInclude) override;
    void visiter(NodeWhile* nodeWhile) override;
    void visiter(NodeOperation* nodeOperation) override;
    void visiter(NodeLiteral* nodeLiteral) override;
    void visiter(NodeNegation* nodeNegation) override;
    void visiter(NodeString* nodeString) override;

protected:
    ContextGenCode* _contextGenCode = nullptr;

};

#endif