#ifndef EXPRESSION_LITERAL_H
#define EXPRESSION_LITERAL_H

#include "compiler/ast/nodes/expression/i_expression_engine.h"
#include "compiler/ast/registry/context_expression.h"

// Do not modify the code; this section is dynamically generated by the Jinja2 template.
class ExpressionLiteral : public IExpressionEngine
{
private:
    ContextExpression& _context;

public:
    ExpressionLiteral(ContextExpression& expressionContext);
    ~ExpressionLiteral() override;

    auto build(std::vector<Token>& equation) -> INode* override;
};

#endif /* EXPRESSION_LITERAL_H */