#ifndef EXPRESSION_STRING_H
#define EXPRESSION_STRING_H

#include "compiler/ast/nodes/expression/i_expression_engine.h"
#include "compiler/ast/registry/context_expression.h"

// Do not modify the code; this section is dynamically generated by the Jinja2 template.
class ExpressionString : public IExpressionEngine
{
private:
    ContextExpression& _context;

public:
    ExpressionString(ContextExpression& expressionContext);
    ~ExpressionString() override;

    auto build(std::vector<Token>& equation) -> INode* override;
};

#endif /* EXPRESSION_STRING_H */