#ifndef EXPRESSION_NEW_H
#define EXPRESSION_NEW_H

#include "compiler/ast/nodes/expression/i_expression_engine.h"
#include "compiler/ast/registry/context_expression.h"

// Do not modify the code; this section is dynamically generated by the Jinja2 template.
class ExpressionNew : public IExpressionEngine
{
private:
    ContextExpression& _context;

public:
    ExpressionNew(ContextExpression& expressionContext);
    ~ExpressionNew() override;

    auto build(std::vector<Token>& equation) -> INode* override;
};

#endif /* EXPRESSION_NEW_H */