#ifndef EXPRESSION_CALLOBJECT_H
#define EXPRESSION_CALLOBJECT_H

#include "compiler/ast/nodes/expression/i_expression_engine.h"
#include "compiler/ast/registry/context_expression.h"

// Do not modify the code; this section is dynamically generated by the Jinja2 template.
class ExpressionCallObject : public IExpressionEngine
{
private:
    ContextExpression& _context;

public:
    ExpressionCallObject(ContextExpression& expressionContext);
    ~ExpressionCallObject() override;

    auto build(std::vector<Token>& equation) -> INode* override;
};

#endif /* EXPRESSION_CALLOBJECT_H */