#ifndef EXPRESSION_CALLFUNCTION_H
#define EXPRESSION_CALLFUNCTION_H

#include "compiler/ast/nodes/expression/i_expression_engine.h"
#include "compiler/ast/registry/context_expression.h"

// Do not modify the code; this section is dynamically generated by the Jinja2 template.
class ExpressionCallFunction : public IExpressionEngine
{
private:
    ContextExpression& _context;

public:
    ExpressionCallFunction(ContextExpression& expressionContext);
    ~ExpressionCallFunction() override;

    auto build(std::vector<Token>& equation) -> INode* override;
};

#endif /* EXPRESSION_CALLFUNCTION_H */