#ifndef AST_GENERE_H
#define AST_GENERE_H

#include "compiler/ast/nodes/interfaces/i_node.h"
#include "compiler/ast/nodes/interfaces/i_expression.h"
#include "compiler/visitor/interfaces/i_visitor.h"
#include <cstddef>
#include <utility>
#include <llvm/ADT/ArrayRef.h>

// Do not modify the code; this section is dynamically generated by the Jinja2 template.
// Enum dynamically generated for all AST nodes
enum class NodeTypeGenerated {
    Instruction,
    CallFunction,
    ArgFunction,
    DeclarationFunction,
    Return,
    AssignmentVariable,
    DeclarationVariable,
    RefVariable,
    UnRefVariable,
    Identifiant,
    AssignmentArray,
    ArrayInitialization,
    ReadingArray,
    Class,
    CallObject,
    AccesAttribute,
    DeclarationObject,
    If,
    New,
    Delete,
    Include,
    While,
    Operation,
    Literal,
    Negation,
    String
};

class NodeInstruction;
class NodeCallFunction;
class NodeArgFunction;
class NodeDeclarationFunction;
class NodeReturn;
class NodeAssignmentVariable;
class NodeDeclarationVariable;
class NodeRefVariable;
class NodeUnRefVariable;
class NodeIdentifiant;
class NodeAssignmentArray;
class NodeArrayInitialization;
class NodeReadingArray;
class NodeClass;
class NodeCallObject;
class NodeAccesAttribute;
class NodeDeclarationObject;
class NodeIf;
class NodeNew;
class NodeDelete;
class NodeInclude;
class NodeWhile;
class NodeOperation;
class NodeLiteral;
class NodeNegation;
class NodeString;


class NodeInstruction : public INode {
public:
    explicit constexpr NodeInstruction(std::size_t p_id) : nodeId(p_id) {}
    ~NodeInstruction() override = default;

public:
    PRYSMA_NODISCARD NodeTypeGenerated getGeneratedType() const override {
        return NodeTypeGenerated::Instruction;
    }

    PRYSMA_NODISCARD static bool classof(const INode* node) {
        return node->getGeneratedType() == NodeTypeGenerated::Instruction;
    }

public:
    PRYSMA_NODISCARD std::size_t getNodeId() const override { return nodeId; }

    void accept(IVisitor* visitor) override {
        visitor->visiter(this);
    }

private:
    std::size_t nodeId;
    
};

class NodeCallFunction : public INode {
public:
    explicit constexpr NodeCallFunction(std::size_t p_id) : nodeId(p_id) {}

public:
    PRYSMA_NODISCARD NodeTypeGenerated getGeneratedType() const override {
         return NodeTypeGenerated::CallFunction;
    }

    PRYSMA_NODISCARD static bool classof(const INode* node) {
         return node->getGeneratedType() == NodeTypeGenerated::CallFunction;
    }

public:
    PRYSMA_NODISCARD std::size_t getNodeId() const override { return nodeId; }

    void accept(IVisitor* visitor) override {
        visitor->visiter(this);
    }

private:
    std::size_t nodeId;

};

class NodeArgFunction : public INode {
public:
    explicit constexpr NodeArgFunction(std::size_t p_id) : nodeId(p_id) {}

public:
    PRYSMA_NODISCARD NodeTypeGenerated getGeneratedType() const override {
         return NodeTypeGenerated::ArgFunction;
    }

    PRYSMA_NODISCARD static bool classof(const INode* node) {
        return node->getGeneratedType() == NodeTypeGenerated::ArgFunction;
    }

public:
    PRYSMA_NODISCARD std::size_t getNodeId() const override { return nodeId; }

    void accept(IVisitor* visitor) override {
        visitor->visiter(this);
    }

private:
    std::size_t nodeId;

};

class NodeDeclarationFunction : public INode {
public:
    explicit constexpr NodeDeclarationFunction(std::size_t p_id) : nodeId(p_id) {}

public:
    PRYSMA_NODISCARD NodeTypeGenerated getGeneratedType() const override {
         return NodeTypeGenerated::DeclarationFunction;
    }

    PRYSMA_NODISCARD static bool classof(const INode* node) {
        return node->getGeneratedType() == NodeTypeGenerated::DeclarationFunction;
    }

public:
    PRYSMA_NODISCARD std::size_t getNodeId() const override { return nodeId; }

    void accept(IVisitor* visitor) override {
        visitor->visiter(this);
    }

private:
    std::size_t nodeId;

};

class NodeReturn : public INode {
public:
    explicit constexpr NodeReturn(std::size_t p_id) : nodeId(p_id) {}

public:
    PRYSMA_NODISCARD NodeTypeGenerated getGeneratedType() const override {
         return NodeTypeGenerated::Return;
    }

    PRYSMA_NODISCARD static bool classof(const INode* node) {
        return node->getGeneratedType() == NodeTypeGenerated::Return;
    }

public:
    PRYSMA_NODISCARD std::size_t getNodeId() const override { return nodeId; }

    void accept(IVisitor* visitor) override {
        visitor->visiter(this);
    }

private:
    std::size_t nodeId;

};

class NodeAssignmentVariable : public INode {
public:
    explicit constexpr NodeAssignmentVariable(std::size_t p_id) : nodeId(p_id) {}

public:
    PRYSMA_NODISCARD NodeTypeGenerated getGeneratedType() const override {
         return NodeTypeGenerated::AssignmentVariable;
    }

    PRYSMA_NODISCARD static bool classof(const INode* node) {
        return node->getGeneratedType() == NodeTypeGenerated::AssignmentVariable;
    }

public:
    PRYSMA_NODISCARD std::size_t getNodeId() const override { return nodeId; }

    void accept(IVisitor* visitor) override {
        visitor->visiter(this);
    }

private:
    std::size_t nodeId;

};

class NodeDeclarationVariable : public INode {
public:
    explicit constexpr NodeDeclarationVariable(std::size_t p_id) : nodeId(p_id) {}

public:
    PRYSMA_NODISCARD NodeTypeGenerated getGeneratedType() const override {
         return NodeTypeGenerated::DeclarationVariable;
    }

    PRYSMA_NODISCARD static bool classof(const INode* node) {
        return node->getGeneratedType() == NodeTypeGenerated::DeclarationVariable;
    }

public:
    PRYSMA_NODISCARD std::size_t getNodeId() const override { return nodeId; }

    void accept(IVisitor* visitor) override {
        visitor->visiter(this);
    }

private:
    std::size_t nodeId;

};

class NodeRefVariable : public INode {
public:
    explicit constexpr NodeRefVariable(std::size_t p_id) : nodeId(p_id) {}

public:
    PRYSMA_NODISCARD NodeTypeGenerated getGeneratedType() const override {
         return NodeTypeGenerated::RefVariable;
    }

    PRYSMA_NODISCARD static bool classof(const INode* node) {
        return node->getGeneratedType() == NodeTypeGenerated::RefVariable;
    }

public:
    PRYSMA_NODISCARD std::size_t getNodeId() const override { return nodeId; }

    void accept(IVisitor* visitor) override {
        visitor->visiter(this);
    }

private:
    std::size_t nodeId;

};

class NodeUnRefVariable : public INode {
public:
    explicit constexpr NodeUnRefVariable(std::size_t p_id) : nodeId(p_id) {}

public:
    PRYSMA_NODISCARD NodeTypeGenerated getGeneratedType() const override {
         return NodeTypeGenerated::UnRefVariable;
    }

    PRYSMA_NODISCARD static bool classof(const INode* node) {
        return node->getGeneratedType() == NodeTypeGenerated::UnRefVariable;
    }

public:
    PRYSMA_NODISCARD std::size_t getNodeId() const override { return nodeId; }

    void accept(IVisitor* visitor) override {
        visitor->visiter(this);
    }

private:
    std::size_t nodeId;

};

class NodeIdentifiant : public INode {
public:
    explicit constexpr NodeIdentifiant(std::size_t p_id) : nodeId(p_id) {}

public:
    PRYSMA_NODISCARD NodeTypeGenerated getGeneratedType() const override {
         return NodeTypeGenerated::Identifiant;
    }

    PRYSMA_NODISCARD static bool classof(const INode* node) {
        return node->getGeneratedType() == NodeTypeGenerated::Identifiant;
    }

public:
    PRYSMA_NODISCARD std::size_t getNodeId() const override { return nodeId; }

    void accept(IVisitor* visitor) override {
        visitor->visiter(this);
    }

private:
    std::size_t nodeId;

};

class NodeAssignmentArray : public INode {
public:
    explicit constexpr NodeAssignmentArray(std::size_t p_id) : nodeId(p_id) {}

public:
    PRYSMA_NODISCARD NodeTypeGenerated getGeneratedType() const override {
         return NodeTypeGenerated::AssignmentArray;
    }

    PRYSMA_NODISCARD static bool classof(const INode* node) {
        return node->getGeneratedType() == NodeTypeGenerated::AssignmentArray;
    }

public:
    PRYSMA_NODISCARD std::size_t getNodeId() const override { return nodeId; }

    void accept(IVisitor* visitor) override {
        visitor->visiter(this);
    }

private:
    std::size_t nodeId;

};

class NodeArrayInitialization : public INode {
public:
    explicit constexpr NodeArrayInitialization(std::size_t p_id) : nodeId(p_id) {}

public:
    PRYSMA_NODISCARD NodeTypeGenerated getGeneratedType() const override {
         return NodeTypeGenerated::ArrayInitialization;
    }

    PRYSMA_NODISCARD static bool classof(const INode* node) {
        return node->getGeneratedType() == NodeTypeGenerated::ArrayInitialization;
    }

public:
    PRYSMA_NODISCARD std::size_t getNodeId() const override { return nodeId; }

    void accept(IVisitor* visitor) override {
        visitor->visiter(this);
    }

private:
    std::size_t nodeId;

};

class NodeReadingArray : public INode {
public:
    explicit constexpr NodeReadingArray(std::size_t p_id) : nodeId(p_id) {}

public:
    PRYSMA_NODISCARD NodeTypeGenerated getGeneratedType() const override {
         return NodeTypeGenerated::ReadingArray;
    }

    PRYSMA_NODISCARD static bool classof(const INode* node) {
        return node->getGeneratedType() == NodeTypeGenerated::ReadingArray;
    }

public:
    PRYSMA_NODISCARD std::size_t getNodeId() const override { return nodeId; }

    void accept(IVisitor* visitor) override {
        visitor->visiter(this);
    }

private:
    std::size_t nodeId;

};

class NodeClass : public INode {
public:
    explicit constexpr NodeClass(std::size_t p_id) : nodeId(p_id) {}

public:
    PRYSMA_NODISCARD NodeTypeGenerated getGeneratedType() const override {
         return NodeTypeGenerated::Class;
    }

    PRYSMA_NODISCARD static bool classof(const INode* node) {
        return node->getGeneratedType() == NodeTypeGenerated::Class;
    }

public:
    PRYSMA_NODISCARD std::size_t getNodeId() const override { return nodeId; }

    void accept(IVisitor* visitor) override {
        visitor->visiter(this);
    }

private:
    std::size_t nodeId;

};

class NodeCallObject : public INode {
public:
    explicit constexpr NodeCallObject(std::size_t p_id) : nodeId(p_id) {}

public:
    PRYSMA_NODISCARD NodeTypeGenerated getGeneratedType() const override {
         return NodeTypeGenerated::CallObject;
    }

    PRYSMA_NODISCARD static bool classof(const INode* node) {
        return node->getGeneratedType() == NodeTypeGenerated::CallObject;
    }

public:
    PRYSMA_NODISCARD std::size_t getNodeId() const override { return nodeId; }

    void accept(IVisitor* visitor) override {
        visitor->visiter(this);
    }

private:
    std::size_t nodeId;

};

class NodeAccesAttribute : public INode {
public:
    explicit constexpr NodeAccesAttribute(std::size_t p_id) : nodeId(p_id) {}

public:
    PRYSMA_NODISCARD NodeTypeGenerated getGeneratedType() const override {
         return NodeTypeGenerated::AccesAttribute;
    }

    PRYSMA_NODISCARD static bool classof(const INode* node) {
        return node->getGeneratedType() == NodeTypeGenerated::AccesAttribute;
    }

public:
    PRYSMA_NODISCARD std::size_t getNodeId() const override { return nodeId; }

    void accept(IVisitor* visitor) override {
        visitor->visiter(this);
    }

private:
    std::size_t nodeId;

};

class NodeDeclarationObject : public INode {
public:
    explicit constexpr NodeDeclarationObject(std::size_t p_id) : nodeId(p_id) {}

public:
    PRYSMA_NODISCARD NodeTypeGenerated getGeneratedType() const override {
         return NodeTypeGenerated::DeclarationObject;
    }

    PRYSMA_NODISCARD static bool classof(const INode* node) {
        return node->getGeneratedType() == NodeTypeGenerated::DeclarationObject;
    }

public:
    PRYSMA_NODISCARD std::size_t getNodeId() const override { return nodeId; }

    void accept(IVisitor* visitor) override {
        visitor->visiter(this);
    }

private:
    std::size_t nodeId;

};

class NodeIf : public INode {
public:
    explicit constexpr NodeIf(std::size_t p_id) : nodeId(p_id) {}

public:
    PRYSMA_NODISCARD NodeTypeGenerated getGeneratedType() const override {
         return NodeTypeGenerated::If;
    }

    PRYSMA_NODISCARD static bool classof(const INode* node) {
        return node->getGeneratedType() == NodeTypeGenerated::If;
    }

public:
    PRYSMA_NODISCARD std::size_t getNodeId() const override { return nodeId; }

    void accept(IVisitor* visitor) override {
        visitor->visiter(this);
    }

private:
    std::size_t nodeId;

};

class NodeNew : public INode {
public:
    explicit constexpr NodeNew(std::size_t p_id) : nodeId(p_id) {}

public:
    PRYSMA_NODISCARD NodeTypeGenerated getGeneratedType() const override {
         return NodeTypeGenerated::New;
    }

    PRYSMA_NODISCARD static bool classof(const INode* node) {
        return node->getGeneratedType() == NodeTypeGenerated::New;
    }

public:
    PRYSMA_NODISCARD std::size_t getNodeId() const override { return nodeId; }

    void accept(IVisitor* visitor) override {
        visitor->visiter(this);
    }

private:
    std::size_t nodeId;

};

class NodeDelete : public INode {
public:
    explicit constexpr NodeDelete(std::size_t p_id) : nodeId(p_id) {}

public:
    PRYSMA_NODISCARD NodeTypeGenerated getGeneratedType() const override {
         return NodeTypeGenerated::Delete;
    }

    PRYSMA_NODISCARD static bool classof(const INode* node) {
        return node->getGeneratedType() == NodeTypeGenerated::Delete;
    }

public:
    PRYSMA_NODISCARD std::size_t getNodeId() const override { return nodeId; }

    void accept(IVisitor* visitor) override {
        visitor->visiter(this);
    }

private:
    std::size_t nodeId;

};

class NodeInclude : public INode {
public:
    explicit constexpr NodeInclude(std::size_t p_id) : nodeId(p_id) {}

public:
    PRYSMA_NODISCARD NodeTypeGenerated getGeneratedType() const override {
         return NodeTypeGenerated::Include;
    }

    PRYSMA_NODISCARD static bool classof(const INode* node) {
        return node->getGeneratedType() == NodeTypeGenerated::Include;
    }

public:
    PRYSMA_NODISCARD std::size_t getNodeId() const override { return nodeId; }

    void accept(IVisitor* visitor) override {
        visitor->visiter(this);
    }

private:
    std::size_t nodeId;

};

class NodeWhile : public INode {
public:
    explicit constexpr NodeWhile(std::size_t p_id) : nodeId(p_id) {}

public:
    PRYSMA_NODISCARD NodeTypeGenerated getGeneratedType() const override {
         return NodeTypeGenerated::While;
    }

    PRYSMA_NODISCARD static bool classof(const INode* node) {
        return node->getGeneratedType() == NodeTypeGenerated::While;
    }

public:
    PRYSMA_NODISCARD std::size_t getNodeId() const override { return nodeId; }

    void accept(IVisitor* visitor) override {
        visitor->visiter(this);
    }

private:
    std::size_t nodeId;

};

class NodeOperation : public IExpression { // NOTE: doit rester IExpression.
public:
    explicit NodeOperation(std::size_t p_id) : nodeId(p_id) {}

public:
    PRYSMA_NODISCARD NodeTypeGenerated getGeneratedType() const override {
         return NodeTypeGenerated::Operation;
    }

    PRYSMA_NODISCARD static bool classof(const INode* node) {
        return node->getGeneratedType() == NodeTypeGenerated::Operation;
    }

public:
    PRYSMA_NODISCARD std::size_t getNodeId() const override { return nodeId; }

    void accept(IVisitor* visitor) override {
        visitor->visiter(this);
    }

private:
    std::size_t nodeId;

};

class NodeLiteral : public INode {
public:
    explicit constexpr NodeLiteral(std::size_t p_id) : nodeId(p_id) {}

public:
    PRYSMA_NODISCARD NodeTypeGenerated getGeneratedType() const override {
         return NodeTypeGenerated::Literal;
    }

    PRYSMA_NODISCARD static bool classof(const INode* node) {
        return node->getGeneratedType() == NodeTypeGenerated::Literal;
    }

public:
    PRYSMA_NODISCARD std::size_t getNodeId() const override { return nodeId; }

    void accept(IVisitor* visitor) override {
        visitor->visiter(this);
    }

private:
    std::size_t nodeId;

};

// OK ÉTANT DONNÉ QUE NOUS AVONS LE TOKENTYPE DANS TOKEN, IL SERAIT PLUS INTELLIGENT DE FAIRE
// UN SEUL SPARSE SET DE TOKENS ET DE FILTRER PAR LA SUITE AVEC TOKENTYPE

// EN FAITE JE NE SAIS PAS... SI JE FAIS UN SEUL, CA COUTE UN IF (TOKEN::TYPE == ...) ET CA GROSSIT
// SIGNIFICATIVEMENT LA TAILLE DU VECTEUR A PARCOURIR SI NOUS AVONS À ITÉRER. 

// D'UN AUTRE COTÉ, ÇA SEMBLE ÉTRANGE DE FAIRE UN SPARSE SET PAR SOUS CATÉGORIE DE COMPOSANTE.
// IL FAUT IMPÉRATIVEMENT TROUVER UNE SOLUTION, AVANCER NE SERA PLUS POSSIBLE TANT QU'IL N'Y 
// AURA PAS EU UN CONSENSUS SUR LA POSITION À ADOPTER. À VOIR.


// class NodeLiteralS : public INode {
// private:
//     NodeTypeGenerated _nodeTypeGenerated = NodeTypeGenerated::Literal;
//     Token _token;

// public:
//     NodeLiteral() = default;    NodeLiteral(Token token) : _token(std::move(token)) {}    ~NodeLiteral() override = default;

//     void accept(IVisitor* visitor) override {
//         visitor->visiter(this);
//     }

//     PRYSMA_NODISCARD NodeTypeGenerated getGeneratedType() const override {
//         return _nodeTypeGenerated;
//     }

//     PRYSMA_NODISCARD static bool classof(const INode* node) {
//         return node->getGeneratedType() == NodeTypeGenerated::Literal;
//     }
//     PRYSMA_NODISCARD const Token& getToken() const { return _token; }
// };

// class NodeLiteral : public INode { // FAIT
// private:
//     NodeTypeGenerated _nodeTypeGenerated = NodeTypeGenerated::Literal;
//     Token _token;

// public:
//     NodeLiteral() = default;    NodeLiteral(Token token) : _token(std::move(token)) {}    ~NodeLiteral() override = default;

//     void accept(IVisitor* visitor) override {
//         visitor->visiter(this);
//     }

//     PRYSMA_NODISCARD NodeTypeGenerated getGeneratedType() const override {
//         return _nodeTypeGenerated;
//     }

//     PRYSMA_NODISCARD static bool classof(const INode* node) {
//         return node->getGeneratedType() == NodeTypeGenerated::Literal;
//     }
//     PRYSMA_NODISCARD const Token& getToken() const { return _token; }
// };




class NodeNegation : public INode {
public:
    explicit constexpr NodeNegation(std::size_t p_id) : nodeId(p_id) {}

public:
    PRYSMA_NODISCARD NodeTypeGenerated getGeneratedType() const override {
         return NodeTypeGenerated::Negation; // LE STOCKER DANS LE REGISTRY
    }

    PRYSMA_NODISCARD static bool classof(const INode* node) { // on dirait qu'il fait la meme chose que l'autre
        return node->getGeneratedType() == NodeTypeGenerated::Negation;
    }

public:
    PRYSMA_NODISCARD std::size_t getNodeId() const override { return nodeId; }

    void accept(IVisitor* visitor) override {
        visitor->visiter(this);
    }

private:
    std::size_t nodeId;

};

// class NodeNegation : public INode {
// private:
//     NodeTypeGenerated _nodeTypeGenerated = NodeTypeGenerated::Negation;
//     Token _operateur;
//     INode* _operande;

// public:
//     NodeNegation() = default;    NodeNegation(Token operateur, INode* operande = nullptr) : _operateur(std::move(operateur)), _operande(operande) {}    ~NodeNegation() override = default;

//     void accept(IVisitor* visitor) override {
//         visitor->visiter(this);
//     }

//     PRYSMA_NODISCARD NodeTypeGenerated getGeneratedType() const override {
//         return _nodeTypeGenerated;
//     }

//     PRYSMA_NODISCARD static bool classof(const INode* node) {
//         return node->getGeneratedType() == NodeTypeGenerated::Negation;
//     }
//     PRYSMA_NODISCARD const Token& getOperateur() const { return _operateur; }
//     PRYSMA_NODISCARD INode* getOperande() const { return _operande; }
// };



class NodeString : public INode {
public:
    explicit constexpr NodeString(std::size_t p_id) : nodeId(p_id) {}

public:
    PRYSMA_NODISCARD NodeTypeGenerated getGeneratedType() const override {
         return NodeTypeGenerated::String; // LE STOCKER DANS LE REGISTRY
    }

    PRYSMA_NODISCARD static bool classof(const INode* node) { // on dirait qu'il fait la meme chose que l'autre
        return node->getGeneratedType() == NodeTypeGenerated::String;
    }

public:
    PRYSMA_NODISCARD std::size_t getNodeId() const override { return nodeId; }

    void accept(IVisitor* visitor) override {
        visitor->visiter(this);
    }

private:
    std::size_t nodeId;

};

// class NodeString : public INode { // FAIT
// private:
//     NodeTypeGenerated _nodeTypeGenerated = NodeTypeGenerated::String;

// public:
//     NodeString() = default;    ~NodeString() override = default;

//     void accept(IVisitor* visitor) override {
//         visitor->visiter(this);
//     }

//     PRYSMA_NODISCARD NodeTypeGenerated getGeneratedType() const override {
//         return _nodeTypeGenerated;
//     }

//     PRYSMA_NODISCARD static bool classof(const INode* node) {
//         return node->getGeneratedType() == NodeTypeGenerated::String;
//     }
// };

#endif