#ifndef VISITEUR_GENERAL_GRAPHVIZ_H
#define VISITEUR_GENERAL_GRAPHVIZ_H

#include "compiler/visual_graph/output_visual_graph_text.h"
#include "compiler/visitor/visitor_base_generale.h"
#include <stack>
#include <vector>

// Do not modify the code; this section is dynamically generated by the Jinja2 template.
class GeneralVisitorGraphViz : public VisitorBaseGenerale
{
private:
    OutputVisualGraphText _outputVisualGraph;
    std::stack<int, std::vector<int>> _pileIds;

public:
    GeneralVisitorGraphViz(ContextGenCode* contextGenCode, OutputVisualGraphText outputVisualGraph);
    ~GeneralVisitorGraphViz() override;
    void generate();

    void visiter(NodeInstruction* nodeInstruction) override;
    void visiter(NodeCallFunction* nodeCallFunction) override;
    void visiter(NodeArgFunction* nodeArgFunction) override;
    void visiter(NodeDeclarationFunction* nodeDeclarationFunction) override;
    void visiter(NodeReturn* nodeReturn) override;
    void visiter(NodeAssignmentVariable* nodeAssignmentVariable) override;
    void visiter(NodeDeclarationVariable* nodeDeclarationVariable) override;
    void visiter(NodeRefVariable* nodeRefVariable) override;
    void visiter(NodeUnRefVariable* nodeUnRefVariable) override;
    void visiter(NodeIdentifiant* nodeIdentifiant) override;
    void visiter(NodeAssignmentArray* nodeAssignmentArray) override;
    void visiter(NodeArrayInitialization* nodeArrayInitialization) override;
    void visiter(NodeReadingArray* nodeReadingArray) override;
    void visiter(NodeClass* nodeClass) override;
    void visiter(NodeCallObject* nodeCallObject) override;
    void visiter(NodeAccesAttribute* nodeAccesAttribute) override;
    void visiter(NodeDeclarationObject* nodeDeclarationObject) override;
    void visiter(NodeIf* nodeIf) override;
    void visiter(NodeNew* nodeNew) override;
    void visiter(NodeDelete* nodeDelete) override;
    void visiter(NodeInclude* nodeInclude) override;
    void visiter(NodeWhile* nodeWhile) override;
    void visiter(NodeOperation* nodeOperation) override;
    void visiter(NodeLiteral* nodeLiteral) override;
    void visiter(NodeNegation* nodeNegation) override;
    void visiter(NodeString* nodeString) override;
};

#endif