#ifndef IVISITEUR_H
#define IVISITEUR_H

class NodeInstruction;
class NodeCallFunction;
class NodeArgFunction;
class NodeDeclarationFunction;
class NodeReturn;
class NodeAssignmentVariable;
class NodeDeclarationVariable;
class NodeRefVariable;
class NodeUnRefVariable;
class NodeIdentifiant;
class NodeAssignmentArray;
class NodeArrayInitialization;
class NodeReadingArray;
class NodeClass;
class NodeCallObject;
class NodeAccesAttribute;
class NodeDeclarationObject;
class NodeIf;
class NodeNew;
class NodeDelete;
class NodeInclude;
class NodeWhile;
class NodeOperation;
class NodeLiteral;
class NodeNegation;
class NodeString;

// Do not modify the code; this section is dynamically generated by the Jinja2 template.
class IVisitor
{
public:
    virtual ~IVisitor() = default;

    virtual void visiter(NodeInstruction* nodeInstruction) = 0;
    virtual void visiter(NodeCallFunction* nodeCallFunction) = 0;
    virtual void visiter(NodeArgFunction* nodeArgFunction) = 0;
    virtual void visiter(NodeDeclarationFunction* nodeDeclarationFunction) = 0;
    virtual void visiter(NodeReturn* nodeReturn) = 0;
    virtual void visiter(NodeAssignmentVariable* nodeAssignmentVariable) = 0;
    virtual void visiter(NodeDeclarationVariable* nodeDeclarationVariable) = 0;
    virtual void visiter(NodeRefVariable* nodeRefVariable) = 0;
    virtual void visiter(NodeUnRefVariable* nodeUnRefVariable) = 0;
    virtual void visiter(NodeIdentifiant* nodeIdentifiant) = 0;
    virtual void visiter(NodeAssignmentArray* nodeAssignmentArray) = 0;
    virtual void visiter(NodeArrayInitialization* nodeArrayInitialization) = 0;
    virtual void visiter(NodeReadingArray* nodeReadingArray) = 0;
    virtual void visiter(NodeClass* nodeClass) = 0;
    virtual void visiter(NodeCallObject* nodeCallObject) = 0;
    virtual void visiter(NodeAccesAttribute* nodeAccesAttribute) = 0;
    virtual void visiter(NodeDeclarationObject* nodeDeclarationObject) = 0;
    virtual void visiter(NodeIf* nodeIf) = 0;
    virtual void visiter(NodeNew* nodeNew) = 0;
    virtual void visiter(NodeDelete* nodeDelete) = 0;
    virtual void visiter(NodeInclude* nodeInclude) = 0;
    virtual void visiter(NodeWhile* nodeWhile) = 0;
    virtual void visiter(NodeOperation* nodeOperation) = 0;
    virtual void visiter(NodeLiteral* nodeLiteral) = 0;
    virtual void visiter(NodeNegation* nodeNegation) = 0;
    virtual void visiter(NodeString* nodeString) = 0;
};

#endif