#ifndef EXPRESSION_ARRAYINITIALIZATION_H
#define EXPRESSION_ARRAYINITIALIZATION_H

#include "compiler/ast/nodes/expression/i_expression_engine.h"
#include "compiler/ast/registry/context_expression.h"

// Do not modify the code; this section is dynamically generated by the Jinja2 template.
class ExpressionArrayInitialization : public IExpressionEngine
{
private:
    ContextExpression& _context;

public:
    ExpressionArrayInitialization(ContextExpression& expressionContext);
    ~ExpressionArrayInitialization() override;

    auto build(std::vector<Token>& equation) -> INode* override;
};

#endif /* EXPRESSION_ARRAYINITIALIZATION_H */