#ifndef EXPRESSION_REFVARIABLE_H
#define EXPRESSION_REFVARIABLE_H

#include "compiler/ast/nodes/expression/i_expression_engine.h"
#include "compiler/ast/registry/context_expression.h"

// Do not modify the code; this section is dynamically generated by the Jinja2 template.
class ExpressionRefVariable : public IExpressionEngine
{
private:
    ContextExpression& _context;

public:
    ExpressionRefVariable(ContextExpression& expressionContext);
    ~ExpressionRefVariable() override;

    auto build(std::vector<Token>& equation) -> INode* override;
};

#endif /* EXPRESSION_REFVARIABLE_H */