#ifndef EXPRESSION_IDENTIFIANT_H
#define EXPRESSION_IDENTIFIANT_H

#include "compiler/ast/nodes/expression/i_expression_engine.h"
#include "compiler/ast/registry/context_expression.h"

// Do not modify the code; this section is dynamically generated by the Jinja2 template.
class ExpressionIdentifiant : public IExpressionEngine
{
private:
    ContextExpression& _context;

public:
    ExpressionIdentifiant(ContextExpression& expressionContext);
    ~ExpressionIdentifiant() override;

    auto build(std::vector<Token>& equation) -> INode* override;
};

#endif /* EXPRESSION_IDENTIFIANT_H */