#ifndef PARSEUR_DECLARATIONVARIABLE_H
#define PARSEUR_DECLARATIONVARIABLE_H

#include "compiler/ast/registry/context_parser.h"
#include "compiler/lexer/lexer.h"
#include "compiler/parser/interfaces/i_parser.h"
#include "compiler/parser/parser_base.h"
#include <cstddef>

// Do not modify the code; this section is dynamically generated by the Jinja2 template.
class ParserDeclarationVariable : public IParser, public ParserBase
{
private:
    ContextParser& _contextParser;
    
public: 

    ParserDeclarationVariable(ContextParser& contextParser);
    ~ParserDeclarationVariable();
    
    auto parse(std::vector<Token>& tokens, std::size_t& index) -> INode* override;
};


#endif /* PARSEUR_DECLARATIONVARIABLE_H */




